disabled_rules:
  - trailing_whitespace
  - line_length
opt_in_rules:
  - explicit_init
  - closure_body_length
  - prefer_self_type_over_type_of_self
included:
  - Sources
  - Tests
excluded:
  - .build
  - Tests/TestcontainersComposeTests/compose_fixtures
