name: Dependency Check (dependabot)

on:
  pull_request:
    paths:
      - 'Package.swift'
      - 'Package.resolved'

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"
      - run: swift package resolve
