name: Dependency Insight

on: push

defaults:
  run:
    working-directory: ./

jobs:
  check-dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Swift
        uses: swift-actions/setup-swift@v3
        with:
          swift-version: "6.1"

      - name: Cache Swift packages
        uses: actions/cache@v5
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Check outdated dependencies
        run: swift package update --dry-run
