name: Format Code (swift-format)

on: push

defaults:
  run:
    working-directory: ./

permissions:
  contents: write

jobs:
  code-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - name: Apply swift-format
        run: swift format --recursive --in-place Sources Tests

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply swift-format
          commit_options: '--no-verify'
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <actions@github.com>
