name: Format Code (swift-format)

on: push

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"
      - run: swift format --recursive --in-place Sources Tests
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Apply swift-format
          commit_options: '--no-verify'
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <actions@github.com>
