name: Lint Code (swiftlint)

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"
      - run: swiftlint lint --strict Sources Tests
