name: Release

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Swift
        uses: swift-actions/setup-swift@v3
        with:
          swift-version: "6.1"

      - name: Semantic release
        uses: mridang/action-semantic-release@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
